### ISSUE TITLE
Не переведено имя Wanda

### ISSUE THREAD

**Issue by mopo3ilo** [CunningFox146/RLP#24]
~~Собственно нет файла rus_names_wanda.tex~~
Посмотрел, как я понял мод в стиме обновляет только файл DST.po.
В репозитории есть файлы, которых нет в загруженном в стиме моде, в том числе и по wanda.
Кстати есть файл [rus_names_wanda.xml](https://github.com/CunningFox146/RLP/blob/wip/images/rus_names_wanda.xml), который ссылается на **rus_names_wanda.tex**, которого нет, но есть [names_wanda.tex](https://github.com/CunningFox146/RLP/blob/wip/images/names_wanda.tex), возможно ошибка в именах/ссылках.

**Comment by FBNikita** [comment]
![image](https://user-images.githubusercontent.com/34344981/154475748-18ed064a-dba2-4107-aa4c-a7b125a549d9.png)

**Comment by FBNikita** [comment]
![image](https://user-images.githubusercontent.com/34344981/154475967-b87acd5b-e7a9-47e3-8b65-690a9c7a2f0a.png)

**Comment by mopo3ilo** [comment]
Не знаком с мастерской стима, возможно там есть разделение модов на операционные системы, у меня linux-версия

**Comment by FBNikita** [comment]
Всё ещё не понимаю вашей проблемы с именем Ванды)
Скриншот из репозитория на сайте. Все файлы присутствуют. Убедитесь, что вы просматриваете версию "wip", а не "master".

**Comment by FBNikita** [comment]
![image](https://user-images.githubusercontent.com/34344981/154502846-7b13c12a-adb3-43a7-bb42-98a7f5d073f5.png)

**Comment by FBNikita** [comment]
Понял о чём идёт речь. И правда, забыл поменять название файла.
Странно что это как-то влияет на игру, т.к. этот спрайт, кажется, уже нигде не используется.

**Comment by mopo3ilo** [comment]
@FBNikita, возможно и правда этот файл не важен.
Но остался вопрос в том, что из мастерской стима устанавливается устаревший мод.

**Comment by FBNikita** [comment]
@mopo3ilo В стиме хранится своя версия модификации, возможность обновить которую утеряна на неопределённое время. Поэтому она подтягивает только файл перевода.
Полное обновление только ручками отсюда.

**Comment by mopo3ilo** [comment]
Ясно, понятно, тогда можно считать проблему решённой
